import React, { useState } from "react";
import { Text, View, Pressable, TextInput, ActivityIndicator } from "react-native";
import { useVerifyPasscodeMutation } from "../../queries/society";
import { useToastStore } from "../../store/useToastStore";
import { ScreenContainer } from "../ui/screen-container";
import { Card } from "../ui/card";

export function CheckPasscodeView() {
  const [code, setCode] = useState("");
  const verifyMutation = useVerifyPasscodeMutation();
  const { showToast } = useToastStore();

  const handleVerify = async () => {
    if (code.length !== 6) {
      showToast("Please enter a valid 6-digit passcode", "error");
      return;
    }

    try {
      const visitor = await verifyMutation.mutateAsync(code);
      showToast(`Access Approved! Pre-approved guest checked in successfully!`, "success");
      setCode("");
    } catch (err: any) {
      showToast(err.message || "Invalid or expired passcode", "error");
    }
  };

  return (
    <ScreenContainer contentContainerStyle={{ padding: 24 }}>
      <Card>
        <Text className="text-foreground-light dark:text-foreground-dark text-xl font-bold mb-2">
          Guest Check-in
        </Text>
        <Text className="text-muted-foreground-light dark:text-muted-foreground-dark text-xs mb-5">
          Enter the 6-digit invitation passcode generated by the resident.
        </Text>

        <View className="gap-5">
          <TextInput
            value={code}
            onChangeText={setCode}
            placeholder="e.g. 123456"
            placeholderTextColor="#78716c"
            keyboardType="number-pad"
            maxLength={6}
            className="bg-muted-light dark:bg-muted-dark border border-border-light dark:border-border-dark text-foreground-light dark:text-foreground-dark rounded-xl py-4 text-center text-3xl font-extrabold tracking-widest focus:border-primary-light dark:focus:border-primary-dark"
          />

          <Pressable
            disabled={verifyMutation.isPending}
            onPress={handleVerify}
            className="bg-primary-light dark:bg-primary-dark rounded-xl py-3.5 mt-2 items-center justify-center active:opacity-90"
          >
            {verifyMutation.isPending ? (
              <ActivityIndicator color="white" />
            ) : (
              <Text className="text-white font-bold text-base">Verify & Grant Access</Text>
            )}
          </Pressable>
        </View>
      </Card>
    </ScreenContainer>
  );
}
export default CheckPasscodeView;
