import React, { useState } from "react";
import { Text, View, Pressable, TextInput, Alert, ActivityIndicator } from "react-native";
import { KeyboardAwareScrollView } from "react-native-keyboard-controller";
import { useVerifyPasscodeMutation } from "../../queries/society";

export function CheckPasscodeView() {
  const [code, setCode] = useState("");
  const verifyMutation = useVerifyPasscodeMutation();

  const handleVerify = async () => {
    if (code.length !== 6) {
      Alert.alert("Error", "Please enter a valid 6-digit passcode");
      return;
    }

    try {
      const visitor = await verifyMutation.mutateAsync(code);
      Alert.alert(
        "Access Approved ✅",
        `Pre-approved guest checked in successfully!\n\nGuest: ${visitor.name}\nFlat: ${visitor.flat.tower.name} - ${visitor.flat.number}`
      );
      setCode("");
    } catch (err: any) {
      Alert.alert("Access Denied ❌", err.message || "Invalid or expired passcode");
    }
  };

  return (
    <KeyboardAwareScrollView
      className="flex-1 bg-zinc-950 px-6 py-4"
      contentContainerStyle={{ paddingBottom: 40 }}
      keyboardShouldPersistTaps="handled"
    >
      <View className="bg-zinc-900 border border-zinc-800 p-5 rounded-2xl">
        <Text className="text-white text-xl font-bold mb-2">Guest Check-in</Text>
        <Text className="text-zinc-400 text-xs mb-5">
          Enter the 6-digit invitation passcode generated by the resident.
        </Text>

        <View className="gap-5">
          <TextInput
            value={code}
            onChangeText={setCode}
            placeholder="e.g. 123456"
            placeholderTextColor="#52525b"
            keyboardType="number-pad"
            maxLength={6}
            className="bg-zinc-950 text-white rounded-xl py-4 text-center text-3xl font-extrabold tracking-widest border border-zinc-800 focus:border-amber-500/50"
          />

          <Pressable
            disabled={verifyMutation.isPending}
            onPress={handleVerify}
            className="bg-amber-600 rounded-xl py-3.5 mt-2 items-center justify-center active:opacity-80"
          >
            {verifyMutation.isPending ? (
              <ActivityIndicator color="white" />
            ) : (
              <Text className="text-white font-bold text-base">Verify & Grant Access</Text>
            )}
          </Pressable>
        </View>
      </View>
    </KeyboardAwareScrollView>
  );
}


